# Generated by Django 4.2.8 on 2024-11-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaccess',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
