# Generated by Django 4.2.8 on 2024-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0002_auto_20241122_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='color',
            field=models.TextField(blank=True),
        ),
    ]
