# Generated by Django 4.2.8 on 2024-12-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0002_auto_20241206_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='data_concessao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
