# Generated by Django 4.2.8 on 2024-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0002_alter_resourceaccess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaccess',
            name='ambiente',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='observacoes',
            field=models.TextField(default='No observations'),
            preserve_default=False,
        ),
    ]
