# Generated by Django 4.2.8 on 2024-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0003_resourceaccess_ambiente_resourceaccess_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='ambiente',
            field=models.CharField(default='Phoebus Local', max_length=30),
            preserve_default=False,
        ),
    ]
