# Generated by Django 4.2.8 on 2024-11-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0003_approver_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approver',
            name='color',
        ),
    ]
