# Generated by Django 4.2.8 on 2024-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0004_alter_resourceaccess_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='aprovador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='tipo_acesso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
