# Generated by Django 4.2.8 on 2024-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0005_alter_resourceaccess_aprovador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaccess',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
