# Generated by Django 4.2.8 on 2024-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0006_resourceaccess_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceaccess',
            name='access',
            field=models.CharField(blank=True),
        ),
    ]
