# Generated by Django 4.2.8 on 2024-11-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0006_alter_resourcegroups_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcegroups',
            options={'ordering': ('groupslist', 'index')},
        ),
        migrations.AddField(
            model_name='resourcegroups',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
