# Generated by Django 4.2.8 on 2024-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0007_resourceaccess_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceaccess',
            name='access',
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='tipo_acesso',
            field=models.CharField(blank=True),
        ),
    ]
