# Generated by Django 4.2.8 on 2024-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0008_remove_resourceaccess_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
