# Generated by Django 4.2.8 on 2024-11-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0009_alter_resourceaccess_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='index',
            field=models.IntegerField(),
        ),
    ]
