# Generated by Django 4.2.8 on 2024-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0011_userlist_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='tags',
        ),
        migrations.AddField(
            model_name='userlist',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
