# Generated by Django 4.2.8 on 2024-11-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0105_customfield_min_max_values'),
        ('netbox_user', '0012_remove_userlist_tags_userlist_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='tags',
        ),
        migrations.AddField(
            model_name='userlist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='extras.tag'),
        ),
    ]
