# Generated by Django 4.2.8 on 2024-11-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0013_remove_userlist_tags_userlist_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='status_user',
            new_name='statususer',
        ),
    ]
