# Generated by Django 4.2.8 on 2024-11-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0014_rename_status_user_userlist_statususer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='statususer',
            new_name='status_user',
        ),
    ]
