# Generated by Django 4.2.8 on 2024-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0015_rename_statususer_userlist_status_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='setor',
            field=models.CharField(default='infraestrutura', max_length=30),
            preserve_default=False,
        ),
    ]
