# Generated by Django 4.2.8 on 2024-11-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0016_userlist_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='data_concessao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='data_expiracao',
            field=models.DateTimeField(),
        ),
    ]
