# Generated by Django 4.2.8 on 2024-11-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0018_remove_resourceaccess_comments_groups_environment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ('environment', 'index')},
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='Environment',
            new_name='environment',
        ),
        migrations.AlterUniqueTogether(
            name='resources',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='environment',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
