# Generated by Django 4.2.8 on 2024-11-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0019_alter_environment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_user.groups'),
            preserve_default=False,
        ),
    ]
