# Generated by Django 4.2.8 on 2024-11-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0021_remove_userlist_groups_userlist_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='groups',
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_user.groups'),
            preserve_default=False,
        ),
    ]
