# Generated by Django 4.2.8 on 2024-11-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0022_remove_userlist_groups_userlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='user',
            new_name='groups',
        ),
    ]
