# Generated by Django 4.2.8 on 2024-11-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0023_rename_user_userlist_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='groups',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_user.groups'),
        ),
    ]
