# Generated by Django 4.2.8 on 2024-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0025_alter_userlist_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='groups',
        ),
        migrations.AddField(
            model_name='userlist',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='rules', to='netbox_user.groups'),
        ),
    ]
