# Generated by Django 4.2.8 on 2024-11-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0026_remove_userlist_groups_userlist_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceaccess',
            name='observacoes',
        ),
    ]
