# Generated by Django 4.2.8 on 2024-11-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0028_approver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approver',
            options={'ordering': ('approver', 'index')},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ('ambiente', 'index')},
        ),
        migrations.RenameField(
            model_name='approver',
            old_name='aprovador',
            new_name='approver',
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='environment',
            new_name='ambiente',
        ),
    ]
