# Generated by Django 4.2.8 on 2024-11-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0029_alter_approver_options_alter_environment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ('grupo', 'index')},
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='group',
            new_name='grupo',
        ),
    ]
