# Generated by Django 4.2.8 on 2024-11-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0030_alter_groups_options_rename_group_groups_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approver',
            options={'ordering': ('aprovador', 'index')},
        ),
        migrations.RenameField(
            model_name='approver',
            old_name='approver',
            new_name='aprovador',
        ),
    ]
