# Generated by Django 4.2.8 on 2024-11-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0031_alter_approver_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceaccess',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='groups',
            field=models.ManyToManyField(blank=True, to='netbox_user.groups'),
        ),
        migrations.AddConstraint(
            model_name='approver',
            constraint=models.UniqueConstraint(fields=('aprovador',), name='unique_aprovador'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('ambiente',), name='unique_ambiente'),
        ),
        migrations.AddConstraint(
            model_name='resourceaccess',
            constraint=models.UniqueConstraint(fields=('user', 'recurso'), name='unique_user_recurso'),
        ),
        migrations.AddConstraint(
            model_name='resources',
            constraint=models.UniqueConstraint(fields=('recurso',), name='unique_recurso'),
        ),
        migrations.RemoveField(
            model_name='resourceaccess',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='resourceaccess',
            name='aprovador',
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='ambiente',
            field=models.ManyToManyField(blank=True, to='netbox_user.environment'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='aprovador',
            field=models.ManyToManyField(blank=True, to='netbox_user.approver'),
        ),
    ]
