# Generated by Django 4.2.8 on 2024-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_user', '0033_sector_sector_unique_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='setor',
        ),
        migrations.AddField(
            model_name='userlist',
            name='setor',
            field=models.ManyToManyField(blank=True, to='netbox_user.sector'),
        ),
    ]
